daily_configs_static = [
    {
        'accessioning_nurses': [50, 45, 297],
        'grossing_nurses': [299, 120, 28, 246, 84, 104, 99, 127, 122],
        'decalcination_nurses': [63, 51],
        'manualEmbedding_nurses': [45, 6],
        'manualSectioning_nurses': [272, 122, ],
        'manualStaining_nurses': [104],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [238, 222, 301],
        'decalcination_nurses_half': [13],
        'manualSectioning_nurses_half': [53, 42, 127, 97],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
    {
        'accessioning_nurses': [78, 281, 27, 297, 278],
        'grossing_nurses': [231, 84, 229],
        'decalcination_nurses': [63, 306, 71],
        'manualEmbedding_nurses': [63, 27, 42, 14, 28],
        'manualSectioning_nurses': [78, 124, 39, 28, 5, 272, 127, 307, 51, 45],
        'manualStaining_nurses': [59, 289, 124, 30],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [],
        'decalcination_nurses_half': [],
        'manualSectioning_nurses_half': [],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
    {
        'accessioning_nurses': [39, 280, 45],
        'grossing_nurses': [233, 15, 71, 90, 13, 104, 30, 63, 84, 304],
        'decalcination_nurses': [122, 45, 18, 124],
        'manualEmbedding_nurses': [127, 18, 90, 104],
        'manualSectioning_nurses': [27, 309, 120, 10, 288, 295, 18],
        'manualStaining_nurses': [289, 23],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [],
        'decalcination_nurses_half': [],
        'manualSectioning_nurses_half': [],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
    {
        'accessioning_nurses': [45, 302],
        'grossing_nurses': [90, 214, 231, 34, 291, 87, 261],
        'decalcination_nurses': [],
        'manualEmbedding_nurses': [27, 28, 53, 306, 5, 57],
        'manualSectioning_nurses': [120, 126, 288, 49, 111, 18, 289, 71, 309, 64, 298, 10],
        'manualStaining_nurses': [124, 28, 13],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [],
        'decalcination_nurses_half': [],
        'manualSectioning_nurses_half': [],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
    {
        'accessioning_nurses': [302, 278, 50],
        'grossing_nurses': [243, 304, 27, 90, 34, 51],
        'decalcination_nurses': [122, 5, 126, 51],
        'manualEmbedding_nurses': [49, 120, 14],
        'manualSectioning_nurses': [32, 53, 303, 126, 298, 78, 28],
        'manualStaining_nurses': [99, 107, 304, 10, 272, 13, 45],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [],
        'decalcination_nurses_half': [],
        'manualSectioning_nurses_half': [],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
    {
        'accessioning_nurses': [6, 39, 78],
        'grossing_nurses': [308, 202, 304, 222, 223, 124, 28, 301, 244, 51, 218],
        'decalcination_nurses': [39, 23, 71],
        'manualEmbedding_nurses': [15, 23, 90, 30, 34, 5],
        'manualSectioning_nurses': [36, 107, 18, 65, 295],
        'manualStaining_nurses': [304, 63],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [],
        'decalcination_nurses_half': [],
        'manualSectioning_nurses_half': [],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
    {
        'accessioning_nurses': [277, 39, 6, 45, 13],
        'grossing_nurses': [63, 13, 289, 254, 71, 124, 214, 233, 222, 39],
        'decalcination_nurses': [],
        'manualEmbedding_nurses': [36, 15],
        'manualSectioning_nurses': [34, 107, 111, 291, 288, 289, 59, 90],
        'manualStaining_nurses': [14, 10, 39, 122, 23],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [],
        'decalcination_nurses_half': [],
        'manualSectioning_nurses_half': [],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
    {
        'accessioning_nurses': [71, 78, 302, 297, 90],
        'grossing_nurses': [5, 231, 214, 246, 107, 301, 229, 71],
        'decalcination_nurses': [45, 34, 53],
        'manualEmbedding_nurses': [120, 53, 18, 89, 84, 126],
        'manualSectioning_nurses': [64, 15, 42, 65, 57],
        'manualStaining_nurses': [10, 50, 59],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [],
        'decalcination_nurses_half': [],
        'manualSectioning_nurses_half': [],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
    {
        'accessioning_nurses': [107, 90, 71],
        'grossing_nurses': [293, 291, 246, 301, 244, 304, 236, 214, 223, 107],
        'decalcination_nurses': [39, 107, 122, 18, 5, 53],
        'manualEmbedding_nurses': [122, 49, 120, 64],
        'manualSectioning_nurses': [313, 89, 59],
        'manualStaining_nurses': [5, 23, 104, 71],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [],
        'decalcination_nurses_half': [],
        'manualSectioning_nurses_half': [],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
    {
        'accessioning_nurses': [27, 297, 39, 6, 107],
        'grossing_nurses': [242, 23, 28, 261, 51, 251, 15, 229],
        'decalcination_nurses': [291, 306, 126, 63, 27],
        'manualEmbedding_nurses': [49, 107, 39, 53, 124, 5],
        'manualSectioning_nurses': [28, 92, 97, 313],
        'manualStaining_nurses': [71, 51],
        'accessioning_nurses_half': [],
        'grossing_nurses_half': [],
        'decalcination_nurses_half': [],
        'manualSectioning_nurses_half': [],
        'manualEmbedding_nurses_half': [],
        'manualStaining_nurses_half': [],
        'finalReportFinished_nurses': [],
        'finalReportFinished_nurses_half': [],
        'num_processing_machines': 1,
        'num_scanning_machines': 2,
        'num_staining_machines': 2,
        'num_stainingIHC_machines': 1,
        'num_automatic_embedding_machines': 1,
    },
]